(function(){
'use strict';
const S=()=>PCXStore,A=()=>PCXApp,$=s=>document.querySelector(s);
const games={
ride:{name:'City Ride',tag:'SÜRÜŞ',category:'action',icon:'garage',desc:'Artan hız, nitro ve sürprizler. Şehrin yeni temposu.',how:'Sola/sağa kaydır veya yön düğmelerini kullan. ← → ve A/D de çalışır. Nitro: ortadaki düğme veya boşluk. Hız zamanla artar. Üç canın var. K kalkan, M mıknatıs, N nitroyu doldurur; koni ve yağdan kaç.',unit:'puan',best:'bestRide',goal:'100 puana ulaş',tone:'ride'},
snake:{name:'Simit Snake',tag:'KLASİK / YENİ',category:'action',icon:'snake',desc:'Simitleri kap, uzamaya devam et. Kuyruk sana ait.',how:'Kaydır, yön düğmelerini veya ok tuşlarını kullan. Simitleri topla; duvara ve kendi kuyruğuna çarpma. Her simit yılanı biraz hızlandırır.',unit:'puan',best:'bestSnake',goal:'50 puana ulaş',tone:'snake'},
breaker:{name:'Brick Garage',tag:'3 ETAP / YENİ',category:'action',icon:'bricks',desc:'Raketi sürükle. Garajın üç duvarını da indir.',how:'Topu bırak; raketi parmağınla sürükleyerek veya ← → düğmeleriyle kontrol et. Boşluk topu bırakır. 3 can, 3 etap. Topu aşağı düşürme.',unit:'puan',best:'bestBreaker',goal:'200 puana ulaş',tone:'breaker'},
helmet:{name:'Kask Avı',tag:'25 SANİYE / YENİ',category:'action',icon:'helmet',desc:'Kaskları yakala. Turuncu koniler belediyenin.',how:'Görünen kaska dokun; koniye dokunma. Seri yakalamalar daha çok puan verir. 25 saniyen ve 3 hata hakkın var. Klavyede 1–9 kutuları seçer.',unit:'puan',best:'bestHelmet',goal:'100 puana ulaş',tone:'helmet'},
lights:{name:'Işıklar Sönsün',tag:'BULMACA / YENİ',category:'calm',icon:'bulb',desc:'Küçük şehrin ışıklarını kapat. Bir hamle, beş etki.',how:'Bir kareye dokunmak onu ve üst/alt/sağ/sol komşularını değiştirir. Tüm ışıkları kapat. Her bulmaca çözülebilir; ipuçları 75 puan düşürür.',unit:'puan',best:'bestLights',goal:'Bir bulmaca çöz',tone:'lights'},
merge:{name:'City 2048',tag:'BULMACA',category:'calm',icon:'grid',desc:'Sayıları birleştir. Kendi hızında 2048’e ulaş.',how:'Dört yöne kaydır veya ok tuşlarına bas. Aynı sayılar birleşir. İlerlemen otomatik saklanır; 5 hamleden sonra turu bitirip puanını alabilirsin.',unit:'puan',best:'bestMerge',goal:'128 puana ulaş',tone:'merge'},
stack:{name:'Sky Stack',tag:'TEK DOKUNUŞ',category:'action',icon:'garage',desc:'Tam zamanında bırak. Şehrin en yüksek kulesini kur.',how:'Hareketli bloğu alttakinin üzerine bırakmak için alana veya YERLEŞTİR’e dokun. Bilgisayarda boşluk tuşu. Kusursuz yerleştirmeler genişliği korur.',unit:'kat',best:'bestStack',goal:'5 kat yüksel',tone:'stack'},
signal:{name:'Signal Loop',tag:'HAFIZA',category:'calm',icon:'spark',desc:'Işıkları izle. Sırayı hatırla, ritmi devam ettir.',how:'Önce yanan numaraları izle, sonra aynı sırayla dokun. Her turda bir ışık eklenir. Klavyede 1–4 tuşları da çalışır.',unit:'tur',best:'bestSignal',goal:'3 tur tamamla',tone:'signal'},
reaction:{name:'Green Light',tag:'REFLEKS',category:'action',icon:'flag',desc:'Yeşili bekle. Tek dokunuşla refleksini ölç.',how:'Beklerken dokunma. Alan yeşil olup ŞİMDİ yazınca bas. Erken dokunursan tur sayılmaz.',unit:'ms',best:'bestReaction',goal:'Bir tur tamamla',tone:'reaction'},
tap:{name:'Tap Rush',tag:'10 SANİYE',category:'action',icon:'bolt',desc:'On saniye. Tek düğme. Kendi rekoruna meydan oku.',how:'Başladıktan sonra büyük düğmeye art arda dokun. İlk dokunuşla 10 saniye başlar. Fare ve boşluk tuşu da kullanılabilir.',unit:'dokunuş',best:'bestTap',goal:'15 kez dokun',tone:'tap'},
memory:{name:'Match Club',tag:'EŞLEŞTİRME',category:'calm',icon:'grid',desc:'Altı çift, küçük bir hafıza molası.',how:'Kartları aç ve aynı sembolleri eşleştir. Süre sınırı yok. Daha az hamle, daha iyi rekor.',unit:'hamle',best:'bestMemory',goal:'Bir tur tamamla',tone:'memory'}
};
let filter='all',goldLooks=0;
function best(id){const g=games[id],s=S().get();return (s.arcade[g.best]??s.stats[g.best])||0;}
function render(){
 const s=S().get(),daily=S().dailyGame();$('#arcadeGameCount').textContent=Object.keys(games).length+' oyun · Senin molan';
 const entries=Object.entries(games).filter(([id,g])=>filter==='all'||filter==='favorites'&&s.arcade.favorites[id]||g.category===filter);
 $('#arcadeGrid').innerHTML=entries.map(([id,g])=>`<article class="arcade-card tone-${g.tone}"><button class="favorite-game" data-favorite="${id}" aria-label="${g.name} favorisi" aria-pressed="${s.arcade.favorites[id]}">${s.arcade.favorites[id]?'★':'☆'}</button><button class="arcade-launch" data-game="${id}"><div class="arcade-art">${art(id)}</div><div class="arcade-info"><span class="tag">${g.tag}</span><h3>${g.name}</h3><p>${g.desc}</p><div class="arcade-meta"><span>${best(id)?'Rekor: '+best(id)+' '+g.unit:'İlk rekorunu bırak'}</span><b>Oyna ↗</b></div></div></button></article>`).join('')||'<div class="empty-arcade"><h3>Favori listen henüz boş.</h3><p>Oyun kartlarındaki yıldıza dokun; sevdiklerin burada toplansın.</p></div>';
 const claimed=s.arcade.bonusDate===S().todayKey();$('#dailyArcade').innerHTML=`<div><span class="kicker">GÜNÜN OYUNU · +150 XP / +60 JETON</span><h2>${games[daily].name}</h2><p>${claimed?'Bugünün bonusu alındı. Yarın yeni bir oyun var.':games[daily].goal+' ve günlük bonusunu kazan.'}</p></div><button class="primary" data-game="${daily}">${claimed?'Yeniden oyna':'Meydan oku'} ↗</button>`;
 const last=s.arcade.lastGame;$('#lastGame').innerHTML=last&&games[last]?`<button class="text-btn" data-game="${last}">Son oynadığın: ${games[last].name} →</button>`:'';
 $('#paintShop').innerHTML=Object.entries(S().PAINTS).map(([id,p])=>`<button class="paint-option ${s.arcade.paint===id?'selected':''} ${id==='gold'?'gold-paint':''}" data-paint="${id}" aria-pressed="${s.arcade.paint===id}"><i style="background:${p.color}"></i><strong>${p.name}</strong><small>${s.arcade.paint===id?'Kullanılıyor':s.arcade.owned[id]?'Seç':p.price+' jeton · Aç'}</small></button>`).join('');
 $('#paintBalance').textContent=s.player.coins+' jeton';
 $('#ridePreview').style.setProperty('--paint',S().PAINTS[s.arcade.paint]?.color||S().PAINTS.sage.color);
 $('#arcadeRecords').innerHTML=Object.entries(games).map(([id,g])=>`<div><span>${g.name}</span><b>${best(id)?best(id)+' '+g.unit:'—'}</b></div>`).join('');
}
function art(id){if(id==='ride')return '<div class="mini-road"><i></i><i></i><b></b><em></em></div>';if(id==='merge')return '<div class="mini-tiles"><b>2</b><b>4</b><b>8</b><b>16</b></div>';if(id==='stack')return '<div class="mini-stack"><i></i><i></i><i></i><i></i></div>';if(id==='signal')return '<div class="mini-signals"><i>1</i><i>2</i><i>3</i><i>4</i></div>';return `<div class="arcade-symbol">${PCXIcon(games[id].icon)}</div>`;}
document.addEventListener('DOMContentLoaded',()=>{
 render();window.addEventListener('pcx:state',render);
 document.addEventListener('click',e=>{const f=e.target.closest('[data-favorite]'),p=e.target.closest('[data-paint]'),tab=e.target.closest('[data-filter]');if(f)S().favorite(f.dataset.favorite);if(p){if(S().paint(p.dataset.paint)){A().toast(p.dataset.paint==='gold'?'Altın Motor hazır. Hava atmak serbest.':'City Ride rengin hazır.');}else{if(p.dataset.paint==='gold'){goldLooks++;if(goldLooks>=5)S().discover('window_shopping');A().toast(['9999 jeton. Motor altın; maaş bordrosu istemiyor.','Vitrine bakmak ücretsiz. Henüz.','Motor: Ben de fiyatımı görünce şaşırdım.'][goldLooks%3]);}else A().toast('Biraz daha jeton gerekli. Oyunlardan kazanabilirsin.');}}if(tab){filter=tab.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',x===tab));render();}});
});
window.PCXArcade={games,best,render};
})();
