(function(){'use strict';
const $=(s,g)=>g.body.querySelector(s),all=(s,g)=>[...g.body.querySelectorAll(s)],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function snake(g){
 g.body.innerHTML='<div class="mini-hud"><span>SİMİT <b id="snakeFood">0</b></span><span>PUAN <b id="snakeScore">0</b></span></div><canvas aria-label="Simit Snake oyun alanı"></canvas><div class="snake-pad"><button data-snake="up" aria-label="Yukarı">↑</button><button data-snake="left" aria-label="Sola">←</button><button data-snake="down" aria-label="Aşağı">↓</button><button data-snake="right" aria-label="Sağa">→</button></div><p class="game-tip">Duvara ve kuyruğuna çarpma. Kaydır veya yönleri kullan.</p>';
 const c=$('canvas',g),ctx=g.canvas(320,320),size=16;let body=[{x:7,y:8},{x:6,y:8},{x:5,y:8}],direction={x:1,y:0},queue=[],food,ate=0,clock=0,down=null;
 const directions={up:{x:0,y:-1},down:{x:0,y:1},left:{x:-1,y:0},right:{x:1,y:0}};
 function spawn(){const free=[];for(let y=0;y<size;y++)for(let x=0;x<size;x++)if(!body.some(p=>p.x===x&&p.y===y))free.push({x,y});if(!free.length){g.finish(ate*25);return;}food=free[Math.floor(Math.random()*free.length)];}
 function turn(name){const d=directions[name],last=queue.at(-1)||direction;if(!d||queue.length>=2||d.x===-last.x&&d.y===-last.y||d.x===last.x&&d.y===last.y)return;queue.push(d);}
 all('[data-snake]',g).forEach(b=>g.action(b,()=>turn(b.dataset.snake)));
 g.on(c,'pointerdown',e=>{if(g.active){down={x:e.clientX,y:e.clientY};c.setPointerCapture(e.pointerId);}});g.on(c,'pointerup',e=>{if(!down||!g.active)return;const dx=e.clientX-down.x,dy=e.clientY-down.y;down=null;if(Math.max(Math.abs(dx),Math.abs(dy))>12)turn(Math.abs(dx)>Math.abs(dy)?dx>0?'right':'left':dy>0?'down':'up');});g.on(c,'pointercancel',()=>down=null);
 spawn();return {pause(){down=null;queue=[];},key(e){const d={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right',w:'up',s:'down',a:'left',d:'right'}[e.key];if(d){e.preventDefault();turn(d);}},update(dt){clock+=dt;const interval=Math.max(.085,.22-ate*.006);if(clock<interval)return;clock-=interval;if(queue.length)direction=queue.shift();const head={x:body[0].x+direction.x,y:body[0].y+direction.y},eat=head.x===food.x&&head.y===food.y,collision=body.slice(0,eat?body.length:-1).some(p=>p.x===head.x&&p.y===head.y);if(head.x<0||head.y<0||head.x>=size||head.y>=size||collision){g.finish(ate*25);return;}body.unshift(head);if(eat){ate++;$('#snakeFood',g).textContent=ate;$('#snakeScore',g).textContent=ate*25;PCXApp.vibrate(7);if(ate===10)PCXStore.discover('snake_10');spawn();}else body.pop();g.status('Simit '+ate+' · Tempo '+(.22/interval).toFixed(1)+'×');},draw(){ctx.fillStyle='#e5edda';ctx.fillRect(0,0,320,320);ctx.strokeStyle='#cddbbb';ctx.lineWidth=.5;for(let i=0;i<=16;i++){ctx.beginPath();ctx.moveTo(i*20,0);ctx.lineTo(i*20,320);ctx.moveTo(0,i*20);ctx.lineTo(320,i*20);ctx.stroke();}body.forEach((p,i)=>{ctx.fillStyle=i?'#658762':'#203d30';ctx.beginPath();ctx.roundRect(p.x*20+2,p.y*20+2,16,16,5);ctx.fill();});ctx.fillStyle='#eff7df';ctx.fillRect(body[0].x*20+10,body[0].y*20+5,3,3);ctx.strokeStyle='#c08a46';ctx.lineWidth=6;ctx.beginPath();ctx.arc(food.x*20+10,food.y*20+10,6,0,Math.PI*2);ctx.stroke();}};
}
function breaker(g){
 g.body.innerHTML='<div class="mini-hud"><span>PUAN <b id="brickScore">0</b></span><span id="brickLevel">ETAP 1/3</span><span>CAN <b id="brickLives">3</b></span></div><canvas aria-label="Brick Garage oyun alanı"></canvas><div class="breaker-controls"><button id="brickLeft" aria-label="Raketi sola taşı">←</button><button id="brickLaunch">Topu bırak</button><button id="brickRight" aria-label="Raketi sağa taşı">→</button></div><p class="game-tip">Raketi parmağınla sürükle. Topu düşürmeden 3 etabı bitir.</p>';
 const canvas=$('canvas',g),ctx=g.canvas(320,400);let px=160,ball={x:160,y:346,vx:70,vy:-180},bricks=[],lives=3,score=0,level=1,launched=false,dragging=false;
 function build(){bricks=[];for(let row=0;row<4;row++)for(let col=0;col<6;col++)bricks.push({x:11+col*50,y:45+row*23,w:46,h:17,on:true,row});}
 function launch(){if(launched)return;launched=true;ball.x=px;ball.y=346;ball.vx=85;ball.vy=-180-level*25;$('#brickLaunch',g).disabled=true;}
 function move(v){px=clamp(v,32,288);if(!launched)ball.x=px;}
 function pointer(e){const r=canvas.getBoundingClientRect();move((e.clientX-r.left)/r.width*320);}
 g.action($('#brickLeft',g),()=>move(px-28));g.action($('#brickRight',g),()=>move(px+28));g.action($('#brickLaunch',g),launch);
 g.on(canvas,'pointerdown',e=>{if(!g.active)return;dragging=true;canvas.setPointerCapture(e.pointerId);pointer(e);launch();});g.on(canvas,'pointermove',e=>{if(g.active&&dragging)pointer(e);});g.on(canvas,'pointerup',()=>dragging=false);g.on(canvas,'pointercancel',()=>dragging=false);
 build();return {pause(){dragging=false;},key(e){if(e.key==='ArrowLeft'){e.preventDefault();move(px-28);}if(e.key==='ArrowRight'){e.preventDefault();move(px+28);}if(e.code==='Space'){e.preventDefault();launch();}},update(dt){if(!launched)return;const steps=Math.ceil(dt/.008);for(let i=0;i<steps;i++){const t=dt/steps,oldY=ball.y;ball.x+=ball.vx*t;ball.y+=ball.vy*t;if(ball.x<7){ball.x=7;ball.vx=Math.abs(ball.vx);}if(ball.x>313){ball.x=313;ball.vx=-Math.abs(ball.vx);}if(ball.y<7){ball.y=7;ball.vy=Math.abs(ball.vy);}
  if(ball.vy>0&&oldY<=353&&ball.y>=353&&Math.abs(ball.x-px)<38){ball.y=353;const speed=220+level*30,ratio=clamp((ball.x-px)/34,-.85,.85);ball.vx=ratio*speed;ball.vy=-Math.sqrt(speed*speed-ball.vx*ball.vx);}
  for(const b of bricks){if(!b.on)continue;const dx=ball.x-clamp(ball.x,b.x,b.x+b.w),dy=ball.y-clamp(ball.y,b.y,b.y+b.h);if(dx*dx+dy*dy<49){b.on=false;score+=25;$('#brickScore',g).textContent=score;if(oldY<b.y||oldY>b.y+b.h)ball.vy=-ball.vy;else ball.vx=-ball.vx;PCXApp.vibrate(4);break;}}
  if(ball.y>410){lives--;$('#brickLives',g).textContent=lives;launched=false;$('#brickLaunch',g).disabled=false;ball={x:px,y:346,vx:85,vy:-200};if(!lives)g.finish(score);return;}
  if(!bricks.some(b=>b.on)){if(level===3){PCXStore.discover('breaker_clear');g.finish(score+300);return;}level++;build();launched=false;ball={x:px,y:346,vx:85,vy:-200};$('#brickLaunch',g).disabled=false;$('#brickLevel',g).textContent='ETAP '+level+'/3';g.status('Bir duvar daha varmış. Etap '+level);return;}
 }},draw(){ctx.fillStyle='#213b33';ctx.fillRect(0,0,320,400);ctx.fillStyle='#324e41';ctx.font='bold 56px sans-serif';ctx.textAlign='center';ctx.fillText('BRICK',160,225);ctx.fillText('GARAGE',160,275);for(const b of bricks)if(b.on){ctx.fillStyle=['#adc6a2','#dfbd80','#db926c','#89b6bd'][b.row];ctx.beginPath();ctx.roundRect(b.x,b.y,b.w,b.h,4);ctx.fill();}ctx.fillStyle='#f6edcb';ctx.beginPath();ctx.roundRect(px-32,360,64,10,5);ctx.fill();ctx.fillStyle='#ef9364';ctx.beginPath();ctx.arc(ball.x,ball.y,7,0,Math.PI*2);ctx.fill();}};
}
function helmet(g){
 g.body.innerHTML='<div class="mini-hud"><span>PUAN <b id="helmetScore">0</b></span><span id="helmetTime">25.0 sn</span><span>HATA <b id="helmetMiss">0</b>/3</span></div><div class="helmet-grid">'+Array.from({length:9},(_,i)=>'<button data-hole="'+i+'" aria-label="Boş alan '+(i+1)+'"><span>·</span></button>').join('')+'</div><p id="helmetTip" class="game-tip" role="status">Kaska dokun, turuncu koniye dokunma.</p>';
 const buttons=all('[data-hole]',g);let left=25,timer=0,index=-1,cone=false,hit=false,score=0,mistakes=0,chain=0;
 function spawn(){if(index>=0&&!hit&&!cone)chain=0;buttons.forEach((b,i)=>{b.className='';b.innerHTML='<span>·</span>';b.setAttribute('aria-label','Boş alan '+(i+1));});const old=index;index=Math.floor(Math.random()*9);if(index===old)index=(index+1)%9;cone=Math.random()<.28;hit=false;buttons[index].className=cone?'pop-cone':'pop-helmet';buttons[index].innerHTML=cone?'<i class="cone-shape"></i>':'<i class="helmet-shape"></i>';buttons[index].setAttribute('aria-label',cone?'Koni, dokunma':'Kask, yakala');timer=Math.max(.48,.95-(25-left)*.015);}
 buttons.forEach((b,i)=>g.action(b,()=>{if(i!==index||hit)return;hit=true;b.classList.add('caught');if(cone){mistakes++;chain=0;$('#helmetMiss',g).textContent=mistakes;$('#helmetTip',g).textContent='O kask değil, belediyenin konisi.';PCXApp.vibrate(20);if(mistakes>=3)g.finish(score);}else{chain++;score+=10+Math.min(20,chain*2);$('#helmetScore',g).textContent=score;$('#helmetTip',g).textContent=chain>=5?'Seri ×'+chain+' · Kask koleksiyoncusu!':'Güzel yakaladın. Turuncuya dikkat.';}}));
 return {start:spawn,key(e){if(/^[1-9]$/.test(e.key)){e.preventDefault();buttons[Number(e.key)-1].click();}},update(dt){left=Math.max(0,left-dt);timer-=dt;$('#helmetTime',g).textContent=left.toFixed(1)+' sn';if(left===0){g.finish(score);return;}if(timer<=0)spawn();g.status('25 saniye · Kaskı yakala');}};
}
function toggle(board,index){const x=index%4,y=Math.floor(index/4);for(const [dx,dy] of [[0,0],[1,0],[-1,0],[0,1],[0,-1]]){const xx=x+dx,yy=y+dy;if(xx>=0&&xx<4&&yy>=0&&yy<4)board[yy*4+xx]=!board[yy*4+xx];}return board;}
function lights(g){
 g.body.innerHTML='<div class="mini-hud"><span>HAMLE <b id="lightsMoves">0</b></span><span id="lightsCount">Işıkları söndür.</span></div><div class="lights-grid" role="group" aria-label="Işık bulmacası">'+Array.from({length:16},(_,i)=>'<button data-light="'+i+'" aria-pressed="false" aria-label="Işık '+(i+1)+'">○</button>').join('')+'</div><div class="puzzle-actions"><button id="lightsHint" class="secondary">İpucu · −75 puan</button><button id="lightsReset" class="secondary">Baştan dene</button></div><p class="game-tip" id="lightsTip" role="status">Bir kare kendisini ve dört komşusunu değiştirir. Hepsini kapat.</p>';
 let board=Array(16).fill(false),solution=Array(16).fill(false),moves=0,hints=0;for(let n=0;n<9;n++){const i=Math.floor(Math.random()*16);toggle(board,i);solution[i]=!solution[i];}if(!board.some(Boolean)){toggle(board,5);solution[5]=!solution[5];}const initial=board.slice(),initialSolution=solution.slice(),buttons=all('[data-light]',g);
 function render(){buttons.forEach((b,i)=>{b.classList.toggle('on',board[i]);b.setAttribute('aria-pressed',String(board[i]));b.textContent=board[i]?'●':'○';b.classList.remove('hinted');});$('#lightsMoves',g).textContent=moves;$('#lightsCount',g).textContent=board.filter(Boolean).length+' ışık açık';}
 buttons.forEach((b,i)=>g.action(b,()=>{toggle(board,i);solution[i]=!solution[i];moves++;render();if(!board.some(Boolean)){PCXStore.discover('lights_clear');g.finish(Math.max(50,1200-moves*20-hints*75));}}));
 g.action($('#lightsHint',g),()=>{const i=solution.findIndex(Boolean);if(i>=0){hints++;buttons[i].classList.add('hinted');$('#lightsTip',g).textContent='Çerçeveli kareye dokun. İpucu '+hints+' · Her biri −75 puan.';}});
 g.action($('#lightsReset',g),()=>{board=initial.slice();solution=initialSolution.slice();moves=0;render();$('#lightsTip',g).textContent='Aynı bulmaca yeniden kuruldu. İpucu kesintisi korunur.';});render();return {start(){g.status('Tüm ışıkları kapat · Süre sınırı yok');}};
}
window.PCXExtraGames={snake,breaker,helmet,lights};window.PCXExtraLogic={toggleLights:toggle};
})();
