(function(){'use strict';const $=s=>document.querySelector(s),S=()=>PCXStore;
function dateLabel(value){return new Date(value).toLocaleString('tr-TR',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'});}
function renderProgress(){const s=S().get(),m=s.progress.missions.date===S().todayKey()?s.progress.missions:{kinds:{},rounds:0},distinct=Object.values(m.kinds).filter(Boolean).length;
const missions=[{id:'explore',title:'Yeni bir şey dene',desc:'2 farklı oyunda birer tur tamamla.',value:distinct,target:2,claimed:m.exploreClaimed,reward:'+120 XP · 45 jeton'},{id:'score',title:'Kısa molalar, büyük ilerleme',desc:'Bugün toplam 5 tur tamamla.',value:m.rounds,target:5,claimed:m.scoreClaimed,reward:'+180 XP · 70 jeton'}];
$('#missionList').innerHTML=missions.map(m=>`<div class="mission"><div class="mission-top"><div><h3>${m.title}</h3><p>${m.desc}</p></div><span>${m.reward}</span></div><div class="progress" role="progressbar" aria-label="${m.title}" aria-valuenow="${Math.min(m.target,m.value||0)}" aria-valuemin="0" aria-valuemax="${m.target}"><i style="width:${Math.min(100,(m.value||0)/m.target*100)}%"></i></div><div class="mission-bottom"><small>${Math.min(m.target,m.value||0)} / ${m.target}</small><button class="secondary" data-mission="${m.id}" ${m.claimed||m.value<m.target?'disabled':''}>${m.claimed?'Ödül alındı ✓':m.value>=m.target?'Ödülü al':'Devam et'}</button></div></div>`).join('');
const plays=s.progress.plays,max=Math.max(1,...Object.values(plays));$('#playStats').innerHTML=Object.entries(plays).map(([id,count])=>`<div class="play-stat"><div><span>${PCXArcade.games[id].name}</span><b>${count} tur</b></div><div class="stat-track"><i style="width:${count/max*100}%"></i></div></div>`).join('');
$('#gameHistory').innerHTML=s.progress.history.length?s.progress.history.slice(0,30).map(h=>`<div class="history-row"><div><b>${PCXArcade.games[h.game].name}</b><small>${dateLabel(h.date)}</small></div><span>${h.value} ${PCXArcade.games[h.game].unit}</span></div>`).join(''):'<div class="personal-empty"><p>Yeni bir tur tamamla.<br>Sonuçların burada biriksin.</p></div>';}

document.addEventListener('DOMContentLoaded',()=>{renderProgress();window.addEventListener('pcx:state',renderProgress);document.addEventListener('click',e=>{const m=e.target.closest('[data-mission]');if(m&&S().claimMission(m.dataset.mission)){PCXApp.toast('Görev ödülü eklendi.');PCXApp.confetti();}});});})();
