(function(){'use strict';
window.PCXCityRide=function(g){
 const $=s=>g.body.querySelector(s),engine=PCXRideEngine.create(),s=engine.state;
 g.body.innerHTML='<div class="ride-hud"><span>PUAN <b id="rideScore">0</b></span><span id="rideLevel">ETAP 01</span><span>CAN <b id="rideLives">3</b></span></div><div class="ride-strip"><span id="rideSpeed">TEMPO 1.0×</span><span id="ridePowers">Şeritlerin hikâyesi başlıyor.</span></div><canvas class="ride-canvas" aria-label="City Ride oyun alanı. Yön düğmeleri ile şerit değiştir."></canvas><p class="ride-event" id="rideEvent" role="status">Motor: Sadece QR’a bakmaya gelmiştin?</p><div class="drive-controls"><button id="driveLeft" aria-label="Sol şerit">←</button><button id="rideBoost" aria-label="Nitroyu kullan"><span>NİTRO</span><b id="boostCharge">100%</b></button><button id="driveRight" aria-label="Sağ şerit">→</button></div>';
 const c=$('canvas'),x=g.canvas(360,450),lanes=[100,180,260],paint=PCXStore.get().arcade.paint,color=PCXStore.PAINTS[paint]?.color||'#b5c9a5';let down=null,messageTime=0,notified=false,prevLives=3;
 const rounded=(a,b,w,h,r,color)=>{x.fillStyle=color;x.beginPath();x.roundRect(a,b,w,h,r);x.fill();};
 function steer(dir){engine.steer(dir);PCXApp.vibrate(5);}
 g.action($('#driveLeft'),()=>steer(-1));g.action($('#driveRight'),()=>steer(1));g.action($('#rideBoost'),()=>engine.boost());
 g.on(c,'pointerdown',e=>{if(!g.active)return;down={x:e.clientX,y:e.clientY};c.setPointerCapture(e.pointerId);});
 g.on(c,'pointerup',e=>{if(!down||!g.active)return;const dx=e.clientX-down.x;if(Math.abs(dx)>15)steer(Math.sign(dx));else steer(e.clientX<c.getBoundingClientRect().left+c.clientWidth/2?-1:1);down=null;});g.on(c,'pointercancel',()=>down=null);
 function car(cx,cy,color){x.save();x.translate(cx,cy);rounded(-24,-37,51,84,12,'#0003');rounded(-22,-40,44,80,10,color);rounded(-17,-24,34,18,5,'#243d49');rounded(-16,13,32,12,4,'#293e47');rounded(-19,-35,9,5,2,'#fce7b5');rounded(10,-35,9,5,2,'#fce7b5');rounded(-19,32,8,4,1,'#e97155');rounded(11,32,8,4,1,'#e97155');x.restore();}
 function scooter(){x.save();x.translate(s.x,365);if(s.invulnerable>0)x.globalAlpha=.7;if(s.shield>0){x.strokeStyle='#b4f0d4';x.lineWidth=3;x.beginPath();x.ellipse(0,0,30,46,0,0,Math.PI*2);x.stroke();}if(s.boost>0){rounded(-9,26,18,34,7,'#ec975c');rounded(-5,29,10,22,5,'#fff1b7');}rounded(-7,-34,14,68,7,'#101c19');rounded(-16,-27,32,48,13,color);rounded(-20,-20,40,7,3,'#d6dfd4');rounded(-10,-28,20,12,5,'#e8f7de');rounded(-11,0,22,23,9,'#293632');x.fillStyle='#3e5145';x.beginPath();x.ellipse(0,-3,18,15,0,0,Math.PI*2);x.fill();x.fillStyle=paint==='gold'?'#ffe398':'#f1e8d3';x.beginPath();x.arc(0,-12,10,0,Math.PI*2);x.fill();rounded(-8,-18,16,5,3,'#53685f');if(paint==='gold'){x.fillStyle='#ffffc1';x.font='18px sans-serif';x.fillText('✦',-28,20);}x.restore();}
 function draw(){const night=s.level%3===0,road=s.distance;x.fillStyle=night?'#243e37':s.level%3===2?'#b2a489':'#91a58b';x.fillRect(0,0,360,450);for(let i=-1;i<6;i++){const y=(i*105+road*.75)%570-70;rounded(4,y,26,45,5,night?'#4c6753':'#68866a');rounded(330,y+30,26,42,5,night?'#53674e':'#68866a');if(night){rounded(9,y+9,6,7,1,'#e1c58b');rounded(336,y+40,6,7,1,'#e1c58b');}}
  x.fillStyle=night?'#c0c5a5':'#d8d5bd';x.fillRect(42,0,9,450);x.fillRect(309,0,9,450);x.fillStyle=night?'#223533':'#394b48';x.fillRect(51,0,258,450);x.fillStyle='#d4d6ba77';for(const xx of [140,220])for(let i=-1;i<10;i++)x.fillRect(xx-1,(i*64+road)%570-65,3,28);
  for(const o of s.objects){const cx=lanes[o.lane],cy=o.y;if(o.kind==='car')car(cx,cy,o.color);else if(o.kind==='cone'){x.fillStyle='#e59254';x.beginPath();x.moveTo(cx,cy-22);x.lineTo(cx-19,cy+19);x.lineTo(cx+19,cy+19);x.closePath();x.fill();rounded(cx-11,cy-1,22,6,2,'#faf1d6');rounded(cx-22,cy+17,44,6,2,'#25372f');}else if(o.kind==='oil'){x.fillStyle='#182a29';x.beginPath();x.ellipse(cx,cy,24,13,.3,0,Math.PI*2);x.fill();}else{x.fillStyle={coin:'#f2cb6d',shield:'#b5e7d4',magnet:'#e3ade3',charge:'#a6d4f6'}[o.kind];x.beginPath();x.arc(cx,cy,13,0,Math.PI*2);x.fill();x.fillStyle='#263d35';x.font='bold 14px sans-serif';x.textAlign='center';x.fillText({coin:'+',shield:'K',magnet:'M',charge:'N'}[o.kind],cx,cy+5);}}
  scooter();if(s.milestone){x.fillStyle='#efd37b';x.font='bold 9px sans-serif';x.textAlign='center';x.fillText('1000',22,35);x.fillText('CLUB',22,47);}
 }
 return {pause(){down=null;},resume(){engine.resume();},key(e){if(['ArrowLeft','a','ArrowRight','d'].includes(e.key)){e.preventDefault();steer(['ArrowLeft','a'].includes(e.key)?-1:1);}if(e.code==='Space'){e.preventDefault();engine.boost();}},update(dt){engine.update(dt);const events=engine.takeEvents();if(events.length){$('#rideEvent').textContent=events[events.length-1];messageTime=4;}else if((messageTime-=dt)<=0)$('#rideEvent').textContent=s.level%3===0?'Gece mesaisi. Farlar bizden.':'Sarı +: jeton · K: kalkan · M: mıknatıs · N: nitro';if(s.milestone&&!notified){notified=true;PCXStore.discover('ride_1000');}if(s.lives<prevLives){prevLives=s.lives;PCXApp.vibrate([25,20,25]);}$('#rideScore').textContent=s.score;$('#rideLives').textContent=s.lives;$('#rideLevel').textContent='ETAP '+String(s.level).padStart(2,'0');$('#rideSpeed').textContent='TEMPO '+(s.speed/190).toFixed(1)+'×';$('#ridePowers').textContent=s.shield>0?'Kalkan '+Math.ceil(s.shield)+' sn':s.magnet>0?'Mıknatıs '+Math.ceil(s.magnet)+' sn':s.oil>0?'Kaygan zemin':'Jeton '+s.coins;$('#boostCharge').textContent=s.boost>0?'AKTİF':Math.floor(s.energy)+'%';$('#rideBoost').disabled=s.energy<100||s.boost>0;g.status('Artan tempo · '+Math.floor(s.time)+' sn');if(s.over)g.finish(s.score);},draw};
};})();
